<#
.SYNOPSIS
  One-time local helper: copy key + user_id from %USERPROFILE%\.grok\auth.json into .env

.DESCRIPTION
  Writes openlife/Tools/usage-budget/.env (gitignored). Does not print the full key.
  Does not modify auth.json. Does not transmit anything.

.EXAMPLE
  .\export-auth-to-env.ps1
#>
[CmdletBinding()]
param(
    [string]$AuthPath = (Join-Path $env:USERPROFILE ".grok\auth.json"),
    [string]$EnvPath = "",
    [switch]$Force
)

$ErrorActionPreference = "Stop"

# Resolve script directory even when dot-sourced or nested PowerShell.
$ScriptDir = $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($ScriptDir)) {
    if ($MyInvocation.MyCommand.Path) {
        $ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
    } else {
        $ScriptDir = (Get-Location).Path
    }
}
if ([string]::IsNullOrWhiteSpace($EnvPath)) {
    $EnvPath = Join-Path $ScriptDir ".env"
}

. (Join-Path $ScriptDir "lib\Load-Env.ps1")

if (-not (Test-Path $AuthPath)) {
    throw "auth.json not found at $AuthPath - run: grok login"
}

if ((Test-Path $EnvPath) -and -not $Force) {
    throw ".env already exists at $EnvPath (use -Force to overwrite)"
}

$store = Get-Content -Raw -Path $AuthPath -Encoding UTF8 | ConvertFrom-Json
$now = [DateTimeOffset]::UtcNow
$pick = $null
foreach ($p in $store.PSObject.Properties) {
    $a = $p.Value
    if (-not $a.key -or -not $a.user_id) { continue }
    $expired = $false
    if ($a.expires_at) {
        try {
            $exp = [DateTimeOffset]::Parse([string]$a.expires_at)
            if ($exp -lt $now.AddMinutes(-2)) { $expired = $true }
        } catch { }
    }
    if ($expired) { continue }
    $pick = $a
    break
}
if (-not $pick) {
    # last resort: first entry with key
    foreach ($p in $store.PSObject.Properties) {
        $a = $p.Value
        if ($a.key -and $a.user_id) { $pick = $a; break }
    }
}
if (-not $pick) {
    throw "No key+user_id found in $AuthPath"
}

# Escape for simple KEY=value (.env): wrap in double quotes if needed
function Escape-EnvValue([string]$v) {
    if ($v -match '[\s#"\\]') {
        $escaped = $v.Replace('\', '\\').Replace('"', '\"')
        return '"' + $escaped + '"'
    }
    return $v
}

$lines = @(
    "# Generated by export-auth-to-env.ps1 - DO NOT COMMIT",
    "# Source: $AuthPath",
    "# Generated (UTC): $([DateTimeOffset]::UtcNow.ToString('o'))",
    "",
    "GROK_API_KEY=$(Escape-EnvValue ([string]$pick.key))",
    "GROK_USER_ID=$(Escape-EnvValue ([string]$pick.user_id))",
    "",
    "# Optional:",
    "# GROK_CLI_CHAT_PROXY_BASE_URL=https://cli-chat-proxy.grok.com/v1"
)

$lines | Set-Content -Path $EnvPath -Encoding utf8

Write-Host "Wrote $EnvPath" -ForegroundColor Green
Write-Host "  GROK_USER_ID = $($pick.user_id)"
Write-Host "  GROK_API_KEY = $(Mask-Secret ([string]$pick.key))"
Write-Host "This file is gitignored. Do not share or commit it." -ForegroundColor Yellow
